<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="10236" started-at="2014-09-12T14:29:47Z" finished-at="2014-09-12T14:29:57Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="10236" started-at="2014-09-12T14:29:47Z" finished-at="2014-09-12T14:29:57Z">
      <class name="skyscape.Launch">
        <test-method status="PASS" signature="setup()[pri:0, instance:skyscape.Launch@7e707e]" name="setup" is-config="true" duration-ms="1304" started-at="2014-09-12T19:59:46Z" finished-at="2014-09-12T19:59:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="Skyscape_website_launch()[pri:0, instance:skyscape.Launch@7e707e]" name="Skyscape_website_launch" duration-ms="9654" started-at="2014-09-12T19:59:47Z" finished-at="2014-09-12T19:59:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Skyscape_website_launch -->
        <test-method status="FAIL" signature="Scroll_down()[pri:0, instance:skyscape.Launch@7e707e]" name="Scroll_down" duration-ms="400" started-at="2014-09-12T19:59:57Z" finished-at="2014-09-12T19:59:57Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertFalse(Assert.java:63)
	at org.testng.Assert.assertFalse(Assert.java:73)
	at skyscape.Launch.Scroll_down(Launch.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Scroll_down -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:skyscape.Launch@7e707e]" name="tearDown" is-config="true" duration-ms="967" started-at="2014-09-12T19:59:58Z" finished-at="2014-09-12T19:59:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- skyscape.Launch -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
